langs = {
    'Python 3': 'python',
    'PyPy3': 'python',
    'C++17': 'c++',
    'C99': 'c',
    'Java 11': 'java',
    'Ruby': 'ruby',
    'Kotlin (JVM)': 'kotlin',
    'Swift': 'swift',
    'Text': 'plain text',
    'C#': 'c#',
    'node.js': 'javascript',
    'Go': 'go',
    'D': 'd',
    'Rust 2018': 'rust',
    'C++17 (Clang)': 'c++',
    'Golfscript': 'javascript',
    'Assembly (32bit)': 'assembly',
    '아희': 'javascript',
    'Java 8': 'java',
    'C11': 'c',
    'C++98': 'c++',
    'C++11': 'c++',
    'C++14': 'c++',
    'Java 8 (OpenJDK)': 'java',
    'C++20': 'c++',
    'Go (gccgo)': 'go',
    'Java 15': 'java',
    'D (LDC)': 'd',
    'PHP': 'php',
    'Rust 2015': 'rust',
    'Rust 2021': 'rust',
    'Pascal': 'pascal',
    'Scala': 'scala',
    'Lua': 'lua',
    'Perl': 'perl',
    'F#': 'f#',
    'Visual Basic': 'visual basic',
    'Objective-C': 'objective-c',
    'Objective-C++': 'objective-c',
    'C99 (Clang)': 'c',
    'C++98 (Clang)': 'c++',
    'C++11 (Clang)': 'c++',
    'C++14 (Clang)': 'c++',
    'C11 (Clang)': 'c',
    'C++20 (Clang)': 'c++',
    'C90': 'c',
    'C2x': 'c',
    'C90 (Clang)': 'c',
    'C2x (Clang)': 'c',
    'TypeScript': 'typescript',
    'Assembly (64bit)': 'assembly',
    'Bash': 'bash',
    'Fortran': 'fortran',
    'Scheme': 'scheme',
    'Ada': 'javascript',
    'awk': 'javascript',
    'OCaml': 'ocaml',
    'Brainfuck': 'javascript',
    'Whitespace': 'javascript',
    'Tcl': 'javascript',
    'Rhino': 'javascript',
    'Pike': 'javascript',
    'sed': 'javascript',
    'INTERCAL': 'javascript',
    'bc': 'javascript',
    'Algol 68': 'javascript',
    'Befunge': 'javascript',
    'FreeBASIC': 'basic',
    'Haxe': 'javascript',
    'LOLCODE': 'javascript',
    'SystemVerilog': 'verilog'
}